spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  config:
    import: configserver:http://config-service:8888
token:
  expiration_time: 864000000
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  rabbitmq:
    host: rabbitmq 
management:  
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
order_service:
  url: http://order-service/order-service/%s/orders
