spring:
token:
  expiration_time: 864000000
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
order_service:
  url: http://order-service/order-service/%s/orders
